name:                instant
author:              "Marta Nowakowska"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- array
- hashmap
- mtl
- filepath
- simple-cmd

library:
  source-dirs: src
executables:
  insc_llvm:
    main:                Main.hs
    other-modules:       []
    source-dirs:         src/llvm
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - instant
  insc_jvm:
    main:                Main.hs
    other-modules:       []
    source-dirs:         src/jvm
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - instant

