name:                instant
author:              "Marta Nowakowska"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- array
- unordered-containers
- mtl
- filepath
- containers # delete
- random # delete

library:
  source-dirs: src

executables:
  instant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - instant
